name: Continuous Integration

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Move Deploy
        run: sh deploy.sh