name: Continuous Integration

on:
  pull_request:
    branches:
      - master

permissions:
      issues: write 

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build application
        run: npm run build
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Deploy
        run: sh deploy.sh
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}